name: HiddenSuggest
version: '${project.version}'
main: com.github.e2318501.hiddensuggest.HiddenSuggest
api-version: '1.19'
permissions:
    hiddensuggest.bypass:
        description: Allows the player to see command suggestions
        default: op
